### PR TITLE
Allow backslash in PHPDoc tag

### PR DESCRIPTION
**Pull request by kubawerlos**
As discussed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6619#issuecomment-1236329281.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Can you please try what's it gonna do with more complicated ORM tags with parentheses and attributes inside?

**Comment by ondrejmirtes** [comment]
It's nice it's not a parse error, but some dedicated node so that this can be read comfortably would be nice, right?

Do you see yourself contributing this, or should I merge the PR as it is?

Thank you.

**Comment by kubawerlos** [comment]
I've stuck on `PhpDocParser::parseTagValue` - a new node would have to be added on that `switch`, right?

Also, I'm not sure if the node should be only for parenthesis and the content inside, or should unpack the content into an array (that probably should handle both `=` and `:` Doctrine's notations, right?).

So I'd like to pass on that, as it might take much longer for you to review and explain to me, that you were doing it yourself :)

**Comment by ondrejmirtes** [comment]
Yeah, this is good enough as it is. Let's address that need when it comes up. I'm gonna release this as a next minor version. Thank you.

**Pull request merged**
