### PR TITLE
Support for `@pure-unless-callable-is-impure`

### PR DESCRIPTION
**Pull request by staabm**
required for https://github.com/phpstan/phpstan/issues/11100

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Pinging some people in the community about an opinion first, stay tuned :)

**Comment by ondrejmirtes** [comment]
Decided to go for it. Other suggestions similar to how Hack handles things are more general, but very complicated to do right now.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by hrach** [comment]
What a missed opportunity to name it `@pure-iff-callable-is-pure`

**Comment by ondrejmirtes** [comment]
`iff` is something math nerds use 😂

**Comment by hrach** [comment]
Maybe an alias? 😇

**Pull request merged**
