### PR TITLE
Remove $trimStrings from ConstExprParser

### PR DESCRIPTION
**Pull request by rvanvelzen**
Per https://github.com/phpstan/phpdoc-parser/pull/143#issuecomment-1281099895

### CODE REVIEW

**Comment by rvanvelzen** [comment]
This should be fine for the next major as it is a BC break.

**Comment by ondrejmirtes** [comment]
I think we could decouple phpdoc-parser version from PHPStan so we could release 2.0 now and update to it in PHPStan 1.x :) On the other hand, this would be a PHPStan-userland BC break too, so it might not be a good idea...

**Comment by ondrejmirtes** [comment]
Just checked in PHPStan and for PHPStan users it's not really a BC break because it's already called with `true`. The only exception are `@method` tags and that's fine...

**Comment by ondrejmirtes** [comment]
Already done in 2.0.x.

**Pull request closed without merging**
